### ISSUE TITLE
As a user, I can log in, so that I can access all of my tasks

### ISSUE THREAD

**Issue by pawelgrimm** [pawelgrimm/pomi#34]
Acceptance criteria:
 - Main app screen redirects to login
 - User can login with Google or create a new account

Sub-tasks:
 - [x] #29 Set up authentication on GCP
 - [x] #30 Create login page
 - [x] #31 Set up authenticated pages
 - [x] #32 Set up authenticated routes
 - [x] #33 Ensure all DB tables store user_id and are linked correctly
