### ISSUE TITLE
As a user I can search existsting projects and tasks, so that I can log my time more accurately.

### ISSUE THREAD

**Issue by pawelgrimm** [pawelgrimm/pomi#38]
Acceptance criteria:
 - Task and project fields show suggestions based on entered search query

Sub-tasks:
 - [ ] #35 Set up redux to store tasks and projects
 - [ ] #36 Set up API to grab tasks and projects
 - [ ] #37 Set up app to fetch task/project updates regularly 
 - [ ] #26 Add task and project searching
